### ISSUE TITLE
Add metainformation panel

### ISSUE THREAD

**Issue by HerrMotz** [HerrMotz/bachelor-thesis#16]
Like in http://rdfexplorer.org

**Comment by HerrMotz** [comment]
Also enhance the search results in the EntitySelectorInput

**Comment by HerrMotz** [comment]
Siehe #21

**Comment by HerrMotz** [comment]
Vielleicht noch Properties im Metainfo Panel anzeigen?

**Comment by PatrickStahl** [comment]
Dabei kann ich mal schauen ob ich Properties, wie Nodes auch, auch per Rechtsklick löschbar mache. Das fand ich zumindest beim Durchklicken von Beispielen immer nervig dass es kein feature ist
