### ISSUE TITLE
Wrong query generation with different properties

### ISSUE THREAD

**Issue by PatrickStahl** [HerrMotz/bachelor-thesis#23]
When adding multiple different connections to a graph the generated SPARQL query can't translate that properly. For example if we create a node with the property 'instance of' everything works fine:
![grafik](https://github.com/user-attachments/assets/9d6dd676-366a-4640-9ed1-d9b73cb90ab7)

But when adding another different property like 'occupation' all properties in the query are changed to the newest one:
![grafik](https://github.com/user-attachments/assets/2680fdd5-749b-4623-9867-9c642fbb90f0)

**Comment by HerrMotz** [comment]
Das ist ja sehr ungüntig
