### ISSUE TITLE
Rework types in App.vue

### ISSUE THREAD

**Issue by HerrMotz** [HerrMotz/bachelor-thesis#27]
![image](https://github.com/user-attachments/assets/e5d07b25-c344-4e94-a53c-c317850f213b)

**Comment by PatrickStahl** [comment]
Kannst du eventuell noch konkretisieren was genau geändert/angepasst werden soll? @HerrMotz

**Comment by HerrMotz** [comment]
Ich habe einen Screenshot von einem Stand gemacht, bei dem der Typ von selectedNode nicht aufgelöst werden konnte. Das hat sich aber scheinbar erledigt.
